// Public application columns. Credentials and visitor tokens never enter this allowlist.
export const tableColumns = {
  user_roles: ["id", "user_id", "role"],
  conversations: ["id", "visitor_name", "created_at", "last_message_at", "admin_read_at"],
  messages: ["id", "conversation_id", "sender", "content", "created_at"],
  patients: [
    "id",
    "name",
    "phone",
    "email",
    "cpf",
    "birth_date",
    "address",
    "guardian_name",
    "guardian_phone",
    "guardian_cpf",
    "gender",
    "responsible_dentist",
    "code",
    "created_at",
  ],
  appointments: ["id", "patient_id", "treatment", "scheduled_at", "status", "created_at"],
  payments: [
    "id",
    "patient_id",
    "appointment_id",
    "status",
    "paid_at",
    "created_at",
    "amount",
    "payment_method",
    "installments",
    "discount",
    "surcharge",
    "cancel_reason",
    "refund_amount",
    "cancelled_at",
    "cancelled_by",
    "description",
  ],
  leads: ["id", "name", "phone", "source", "status", "created_at"],
  treatments: ["id", "name", "description", "duration_minutes", "active", "created_at", "price"],
  budgets: ["id", "patient_id", "treatment", "status", "notes", "created_at", "value"],
  prescriptions: ["id", "patient_id", "medication", "instructions", "issued_at", "created_at"],
  documents: ["id", "patient_id", "prescription_id", "title", "category", "url", "created_at"],
  whatsapp_contacts: ["id", "name", "phone", "last_message", "last_contact_at", "created_at"],
  services: ["id", "name", "description", "active", "sort_order", "created_at", "price"],
  profiles: ["id", "display_name", "created_at"],
  clinic_settings: [
    "id",
    "clinic_name",
    "phone",
    "address",
    "instagram_url",
    "facebook_url",
    "whatsapp_number",
    "dentist_name",
    "dentist_cro",
    "clinic_email",
    "clinic_city",
    "updated_at",
    "ai_secretary_enabled",
    "disabled_modules",
    "disabled_payment_methods",
    "module_order",
    "adsense_enabled",
    "adsense_client_id",
    "adsense_slot_home",
    "adsense_slot_blog_list",
    "adsense_slot_blog_post",
    "ads_txt_extra",
  ],
  blog_posts: [
    "id",
    "title",
    "slug",
    "excerpt",
    "content",
    "cover_image_url",
    "status",
    "published_at",
    "created_at",
    "updated_at",
    "category",
  ],
  patient_anamnesis: [
    "patient_id",
    "chief_complaint",
    "last_dental_visit_at",
    "brushing_frequency",
    "flosses_regularly",
    "bleeding_gums",
    "tooth_sensitivity",
    "bruxism",
    "uses_orthodontic_appliance",
    "uses_dental_prosthesis",
    "anesthesia_allergy",
    "allergies",
    "current_medications",
    "systemic_conditions",
    "previous_surgeries",
    "is_smoker",
    "is_pregnant",
    "has_diabetes",
    "has_hypertension",
    "has_heart_condition",
    "additional_notes",
    "updated_at",
  ],
  tooth_records: ["id", "patient_id", "tooth_number", "conditions", "notes", "updated_at"],
  site_content: ["id", "content", "updated_at"],
  // image_data never enters this allowlist (see migration 0008).
  site_images: ["id", "slot", "mime_type", "width", "height", "byte_size", "created_at"],
  document_templates: [
    "id",
    "kind",
    "name",
    "title",
    "body",
    "layout",
    "sort_order",
    "created_at",
    "updated_at",
  ],
  tooth_procedures: [
    "id",
    "patient_id",
    "tooth_number",
    "surfaces",
    "situation",
    "planned_procedure",
    "status",
    "notes",
    "record_date",
    "dentist",
    "created_at",
    "price",
    "budget_id",
  ],
  // image_data never enters this allowlist (see migration 0004).
  tooth_attachments: [
    "id",
    "patient_id",
    "procedure_id",
    "tooth_number",
    "title",
    "mime_type",
    "byte_size",
    "created_at",
  ],
  clinical_notes: ["id", "patient_id", "note", "created_at"],
  ai_search_history: ["id", "question", "answer", "created_at"],
  gallery_photos: [
    "id",
    "title",
    "mime_type",
    "width",
    "height",
    "byte_size",
    "sort_order",
    "created_at",
  ],
  finance_entries: [
    "id",
    "type",
    "description",
    "category",
    "amount",
    "due_date",
    "paid_at",
    "status",
    "patient_id",
    "notes",
    "created_at",
    "payment_method",
    "installments",
  ],
} as const;
export type TableName = keyof typeof tableColumns;
