/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ServicosRouteImport } from './routes/servicos'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as AdminBackupRouteImport } from './routes/admin/backup'
import { Route as AdminCaixaRouteImport } from './routes/admin/caixa'
import { Route as AdminCmsSiteRouteImport } from './routes/admin/cms-site'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminContasRouteImport } from './routes/admin/contas'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminDocumentosRouteImport } from './routes/admin/documentos'
import { Route as AdminFinanceiroRouteImport } from './routes/admin/financeiro'
import { Route as AdminIaRouteImport } from './routes/admin/ia'
import { Route as AdminModelosRouteImport } from './routes/admin/modelos'
import { Route as AdminOdontogramaRouteImport } from './routes/admin/odontograma'
import { Route as AdminOrcamentosRouteImport } from './routes/admin/orcamentos'
import { Route as AdminPacientesRouteImport } from './routes/admin/pacientes'
import { Route as AdminReceitasRouteImport } from './routes/admin/receitas'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminSuporteRouteImport } from './routes/admin/suporte'
import { Route as AdminTratamentosRouteImport } from './routes/admin/tratamentos'
import { Route as AdminTutorialRouteImport } from './routes/admin/tutorial'
import { Route as AdminWhatsappRouteImport } from './routes/admin/whatsapp'
import { Route as BlogSlugRouteImport } from './routes/blog_.$slug'
import { Route as AdminPacientesPatientIdRouteImport } from './routes/admin/pacientes_.$patientId'
import { Route as AdminPacientesPatientIdPropostaRouteImport } from './routes/admin/pacientes_.$patientId_.proposta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosRoute = ServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBackupRoute = AdminBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCaixaRoute = AdminCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsSiteRoute = AdminCmsSiteRouteImport.update({
  id: '/cms-site',
  path: '/cms-site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContasRoute = AdminContasRouteImport.update({
  id: '/contas',
  path: '/contas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDocumentosRoute = AdminDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceiroRoute = AdminFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelosRoute = AdminModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOdontogramaRoute = AdminOdontogramaRouteImport.update({
  id: '/odontograma',
  path: '/odontograma',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrcamentosRoute = AdminOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesRoute = AdminPacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReceitasRoute = AdminReceitasRouteImport.update({
  id: '/receitas',
  path: '/receitas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSuporteRoute = AdminSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTratamentosRoute = AdminTratamentosRouteImport.update({
  id: '/tratamentos',
  path: '/tratamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTutorialRoute = AdminTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog_/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPacientesPatientIdRoute = AdminPacientesPatientIdRouteImport.update({
  id: '/pacientes_/$patientId',
  path: '/pacientes/$patientId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPacientesPatientIdPropostaRoute =
  AdminPacientesPatientIdPropostaRouteImport.update({
    id: '/pacientes_/$patientId_/proposta',
    path: '/pacientes/$patientId/proposta',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/termos': typeof TermosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/caixa': typeof AdminCaixaRoute
  '/admin/cms-site': typeof AdminCmsSiteRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/odontograma': typeof AdminOdontogramaRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pacientes': typeof AdminPacientesRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tratamentos': typeof AdminTratamentosRoute
  '/admin/tutorial': typeof AdminTutorialRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pacientes/$patientId': typeof AdminPacientesPatientIdRoute
  '/admin/pacientes/$patientId/proposta': typeof AdminPacientesPatientIdPropostaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/termos': typeof TermosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/caixa': typeof AdminCaixaRoute
  '/admin/cms-site': typeof AdminCmsSiteRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/odontograma': typeof AdminOdontogramaRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pacientes': typeof AdminPacientesRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tratamentos': typeof AdminTratamentosRoute
  '/admin/tutorial': typeof AdminTutorialRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/pacientes/$patientId': typeof AdminPacientesPatientIdRoute
  '/admin/pacientes/$patientId/proposta': typeof AdminPacientesPatientIdPropostaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/contato': typeof ContatoRoute
  '/entrar': typeof EntrarRoute
  '/galeria': typeof GaleriaRoute
  '/privacidade': typeof PrivacidadeRoute
  '/servicos': typeof ServicosRoute
  '/termos': typeof TermosRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/backup': typeof AdminBackupRoute
  '/admin/caixa': typeof AdminCaixaRoute
  '/admin/cms-site': typeof AdminCmsSiteRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/contas': typeof AdminContasRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/documentos': typeof AdminDocumentosRoute
  '/admin/financeiro': typeof AdminFinanceiroRoute
  '/admin/ia': typeof AdminIaRoute
  '/admin/modelos': typeof AdminModelosRoute
  '/admin/odontograma': typeof AdminOdontogramaRoute
  '/admin/orcamentos': typeof AdminOrcamentosRoute
  '/admin/pacientes': typeof AdminPacientesRoute
  '/admin/receitas': typeof AdminReceitasRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/suporte': typeof AdminSuporteRoute
  '/admin/tratamentos': typeof AdminTratamentosRoute
  '/admin/tutorial': typeof AdminTutorialRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/blog_/$slug': typeof BlogSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/pacientes_/$patientId': typeof AdminPacientesPatientIdRoute
  '/admin/pacientes_/$patientId_/proposta': typeof AdminPacientesPatientIdPropostaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/contato'
    | '/entrar'
    | '/galeria'
    | '/privacidade'
    | '/servicos'
    | '/termos'
    | '/admin/agenda'
    | '/admin/backup'
    | '/admin/caixa'
    | '/admin/cms-site'
    | '/admin/configuracoes'
    | '/admin/contas'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/documentos'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/modelos'
    | '/admin/odontograma'
    | '/admin/orcamentos'
    | '/admin/pacientes'
    | '/admin/receitas'
    | '/admin/relatorios'
    | '/admin/suporte'
    | '/admin/tratamentos'
    | '/admin/tutorial'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/admin/'
    | '/admin/pacientes/$patientId'
    | '/admin/pacientes/$patientId/proposta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/contato'
    | '/entrar'
    | '/galeria'
    | '/privacidade'
    | '/servicos'
    | '/termos'
    | '/admin/agenda'
    | '/admin/backup'
    | '/admin/caixa'
    | '/admin/cms-site'
    | '/admin/configuracoes'
    | '/admin/contas'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/documentos'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/modelos'
    | '/admin/odontograma'
    | '/admin/orcamentos'
    | '/admin/pacientes'
    | '/admin/receitas'
    | '/admin/relatorios'
    | '/admin/suporte'
    | '/admin/tratamentos'
    | '/admin/tutorial'
    | '/admin/whatsapp'
    | '/blog/$slug'
    | '/admin'
    | '/admin/pacientes/$patientId'
    | '/admin/pacientes/$patientId/proposta'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/contato'
    | '/entrar'
    | '/galeria'
    | '/privacidade'
    | '/servicos'
    | '/termos'
    | '/admin/agenda'
    | '/admin/backup'
    | '/admin/caixa'
    | '/admin/cms-site'
    | '/admin/configuracoes'
    | '/admin/contas'
    | '/admin/crm'
    | '/admin/dashboard'
    | '/admin/documentos'
    | '/admin/financeiro'
    | '/admin/ia'
    | '/admin/modelos'
    | '/admin/odontograma'
    | '/admin/orcamentos'
    | '/admin/pacientes'
    | '/admin/receitas'
    | '/admin/relatorios'
    | '/admin/suporte'
    | '/admin/tratamentos'
    | '/admin/tutorial'
    | '/admin/whatsapp'
    | '/blog_/$slug'
    | '/admin/'
    | '/admin/pacientes_/$patientId'
    | '/admin/pacientes_/$patientId_/proposta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  ContatoRoute: typeof ContatoRoute
  EntrarRoute: typeof EntrarRoute
  GaleriaRoute: typeof GaleriaRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ServicosRoute: typeof ServicosRoute
  TermosRoute: typeof TermosRoute
  BlogSlugRoute: typeof BlogSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos': {
      id: '/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof ServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/backup': {
      id: '/admin/backup'
      path: '/backup'
      fullPath: '/admin/backup'
      preLoaderRoute: typeof AdminBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/caixa': {
      id: '/admin/caixa'
      path: '/caixa'
      fullPath: '/admin/caixa'
      preLoaderRoute: typeof AdminCaixaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms-site': {
      id: '/admin/cms-site'
      path: '/cms-site'
      fullPath: '/admin/cms-site'
      preLoaderRoute: typeof AdminCmsSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contas': {
      id: '/admin/contas'
      path: '/contas'
      fullPath: '/admin/contas'
      preLoaderRoute: typeof AdminContasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/documentos': {
      id: '/admin/documentos'
      path: '/documentos'
      fullPath: '/admin/documentos'
      preLoaderRoute: typeof AdminDocumentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/financeiro': {
      id: '/admin/financeiro'
      path: '/financeiro'
      fullPath: '/admin/financeiro'
      preLoaderRoute: typeof AdminFinanceiroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ia': {
      id: '/admin/ia'
      path: '/ia'
      fullPath: '/admin/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modelos': {
      id: '/admin/modelos'
      path: '/modelos'
      fullPath: '/admin/modelos'
      preLoaderRoute: typeof AdminModelosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/odontograma': {
      id: '/admin/odontograma'
      path: '/odontograma'
      fullPath: '/admin/odontograma'
      preLoaderRoute: typeof AdminOdontogramaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orcamentos': {
      id: '/admin/orcamentos'
      path: '/orcamentos'
      fullPath: '/admin/orcamentos'
      preLoaderRoute: typeof AdminOrcamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacientes': {
      id: '/admin/pacientes'
      path: '/pacientes'
      fullPath: '/admin/pacientes'
      preLoaderRoute: typeof AdminPacientesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/receitas': {
      id: '/admin/receitas'
      path: '/receitas'
      fullPath: '/admin/receitas'
      preLoaderRoute: typeof AdminReceitasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/suporte': {
      id: '/admin/suporte'
      path: '/suporte'
      fullPath: '/admin/suporte'
      preLoaderRoute: typeof AdminSuporteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tratamentos': {
      id: '/admin/tratamentos'
      path: '/tratamentos'
      fullPath: '/admin/tratamentos'
      preLoaderRoute: typeof AdminTratamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tutorial': {
      id: '/admin/tutorial'
      path: '/tutorial'
      fullPath: '/admin/tutorial'
      preLoaderRoute: typeof AdminTutorialRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog_/$slug': {
      id: '/blog_/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pacientes_/$patientId': {
      id: '/admin/pacientes_/$patientId'
      path: '/pacientes/$patientId'
      fullPath: '/admin/pacientes/$patientId'
      preLoaderRoute: typeof AdminPacientesPatientIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pacientes_/$patientId_/proposta': {
      id: '/admin/pacientes_/$patientId_/proposta'
      path: '/pacientes/$patientId/proposta'
      fullPath: '/admin/pacientes/$patientId/proposta'
      preLoaderRoute: typeof AdminPacientesPatientIdPropostaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminBackupRoute: typeof AdminBackupRoute
  AdminCaixaRoute: typeof AdminCaixaRoute
  AdminCmsSiteRoute: typeof AdminCmsSiteRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminContasRoute: typeof AdminContasRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDocumentosRoute: typeof AdminDocumentosRoute
  AdminFinanceiroRoute: typeof AdminFinanceiroRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminModelosRoute: typeof AdminModelosRoute
  AdminOdontogramaRoute: typeof AdminOdontogramaRoute
  AdminOrcamentosRoute: typeof AdminOrcamentosRoute
  AdminPacientesRoute: typeof AdminPacientesRoute
  AdminReceitasRoute: typeof AdminReceitasRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSuporteRoute: typeof AdminSuporteRoute
  AdminTratamentosRoute: typeof AdminTratamentosRoute
  AdminTutorialRoute: typeof AdminTutorialRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPacientesPatientIdRoute: typeof AdminPacientesPatientIdRoute
  AdminPacientesPatientIdPropostaRoute: typeof AdminPacientesPatientIdPropostaRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminBackupRoute: AdminBackupRoute,
  AdminCaixaRoute: AdminCaixaRoute,
  AdminCmsSiteRoute: AdminCmsSiteRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminContasRoute: AdminContasRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDocumentosRoute: AdminDocumentosRoute,
  AdminFinanceiroRoute: AdminFinanceiroRoute,
  AdminIaRoute: AdminIaRoute,
  AdminModelosRoute: AdminModelosRoute,
  AdminOdontogramaRoute: AdminOdontogramaRoute,
  AdminOrcamentosRoute: AdminOrcamentosRoute,
  AdminPacientesRoute: AdminPacientesRoute,
  AdminReceitasRoute: AdminReceitasRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSuporteRoute: AdminSuporteRoute,
  AdminTratamentosRoute: AdminTratamentosRoute,
  AdminTutorialRoute: AdminTutorialRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminPacientesPatientIdRoute: AdminPacientesPatientIdRoute,
  AdminPacientesPatientIdPropostaRoute: AdminPacientesPatientIdPropostaRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  ContatoRoute: ContatoRoute,
  EntrarRoute: EntrarRoute,
  GaleriaRoute: GaleriaRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ServicosRoute: ServicosRoute,
  TermosRoute: TermosRoute,
  BlogSlugRoute: BlogSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
