-- Odontograma profissional: dados extras do paciente, histórico de
-- procedimentos por dente (com faces) e anexos (fotos/radiografias).

alter table patients add column if not exists gender varchar(20);
alter table patients add column if not exists responsible_dentist text;
alter table patients add column if not exists code bigint generated by default as identity;

create table if not exists tooth_procedures (
  id text primary key default gen_random_uuid()::text,
  patient_id text not null references patients(id) on delete restrict,
  tooth_number smallint not null check (tooth_number between 11 and 48 or tooth_number between 51 and 85),
  surfaces jsonb not null default '[]'::jsonb,
  situation varchar(40) not null,
  planned_procedure varchar(40),
  status varchar(20) not null default 'planejado'
    check (status in ('planejado', 'em_andamento', 'concluido')),
  notes text,
  record_date date not null default current_date,
  dentist text,
  created_at timestamptz(3) not null default now()
);
create index if not exists idx_tooth_procedures_patient on tooth_procedures (patient_id, tooth_number);

-- image_data nunca entra em tableColumns: só o upload (servidor) e a rota
-- /api/tooth-attachments/:id (somente administradores) leem os bytes.
create table if not exists tooth_attachments (
  id text primary key default gen_random_uuid()::text,
  patient_id text not null references patients(id) on delete restrict,
  procedure_id text references tooth_procedures(id) on delete cascade,
  tooth_number smallint not null,
  title text,
  mime_type varchar(100) not null,
  byte_size int not null,
  image_data bytea not null,
  created_at timestamptz(3) not null default now()
);
create index if not exists idx_tooth_attachments_patient on tooth_attachments (patient_id, tooth_number);

do $$
declare t text;
begin
  foreach t in array array['tooth_procedures', 'tooth_attachments'] loop
    execute format('alter table %I enable row level security', t);
    if exists (select 1 from pg_roles where rolname = 'anon') then
      execute format('revoke all on table %I from anon, authenticated', t);
    end if;
  end loop;
end $$;
